# Use official Python image
FROM python:3.11-slim

# Set work directory
WORKDIR /app

COPY ./docker/api ./app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app code
COPY ./app ./app

# Command to run the app
CMD ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"]